### ISSUE TITLE
Font is not changed in the overlay

### ISSUE THREAD

**Issue by LONGACAT** [Overimagine1/old-discord-font#3]
Overlay:
![image](https://user-images.githubusercontent.com/31207198/205702314-c9384376-1b98-4bd2-9c94-ab982d78f654.png)
App:
![image](https://user-images.githubusercontent.com/31207198/205702241-b326e79b-4cdf-4dd4-b56c-c91907bc6b16.png)

**Comment by Overimagine1** [comment]
There's unfortunately nothing I can do about it considering that no client mod supports theming the overlay. If something adds overlay theming then I can add support for that, but other than that it's impossible.
