### ISSUE TITLE
Shrug is not reverted

### ISSUE THREAD

**Issue by BlendyDev** [Overimagine1/old-discord-font#4]

**Comment by Overimagine1** [comment]
Seems reverted to me. Top is without the CSS and bottom is with.
![image](https://user-images.githubusercontent.com/79660414/206935259-1ccb2117-69e8-4fa3-972a-b4e4fb61e660.png)
![image](https://user-images.githubusercontent.com/79660414/206935283-95734220-4ca7-4721-86c0-cb60b74257e6.png)

**Comment by BlendyDev** [comment]
![image](https://user-images.githubusercontent.com/63923395/207132743-c26eebc0-9cb4-40b1-ae06-26e6ab24e430.png)
the shrug (well the japanese char itself) has been like this ever since discord changed fonts. When installing the theme it didn't revert

**Comment by caveguy427** [comment]
i don't usually talk with other people and i don't know much about css, so i don't know if i'll be doing something that wouldn't be good
i tried adding another font in `--font-japanese` in the css (like `--font-japanese:"MS Gothic",Whitney,...`)
it looked like that font was only used when i added it in `--font-primary` though

**Comment by Overimagine1** [comment]
Fixed with the latest commit
