### ISSUE TITLE
fonts not used when display language is cjk

### ISSUE THREAD

**Issue by caveguy427** [Overimagine1/old-discord-font#5]
i don't know much about css so i don't know what would be a good fix
the fonts in the css (old fonts) aren't used when the display language is set as chinese, japanese or korean
i tried editing this line to `:root,:Lang(ko),:Lang(ja),:Lang(zh-CN),:Lang(zh-TW){` in the css and those were used:
https://github.com/Overimagine1/old-discord-font/blob/a54dd5790c3ef984b903482811219e60d24e63f1/source.css#L170

**Comment by Overimagine1** [comment]
Fixed
