### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by Juicyousiguy** [Overimagine1/old-discord-font#6]
i use vencord, and ive tried using the link and custom css, and neither have worked

**Comment by Overimagine1** [comment]
Can you screenshot your Vencord themes section?

**Comment by Juicyousiguy** [comment]
![image](https://github.com/Overimagine1/old-discord-font/assets/36769342/dcb144ad-36ab-4923-93ce-c7393ac78a6a)

**Comment by Overimagine1** [comment]
Try using this
`https://overimagine1.github.io/old-discord-font/source.css`

**Comment by Juicyousiguy** [comment]
it says it's valid, but i dont see any noticable difference in the fonts

**Comment by Overimagine1** [comment]
Sorry, I'm busy with college so I don't have much time with GH. Are you sure your isp isn't blocking those domains? Try them on a VPN or a different dns.

**Comment by FerroSan** [comment]
It doesn't work anymore. A recent discord update has bricked custom themes on Vencord and I assume BD. Is it currently possible to fix this? 
Here's an image of Vencord's validator and a cloud settings notice:
![image](https://github.com/Overimagine1/old-discord-font/assets/33472406/1a426014-7b6c-444d-abfb-a5c62a520f34)
![image](https://github.com/Overimagine1/old-discord-font/assets/33472406/daadac0f-1268-4719-94bb-759e348a503d)

**Comment by Overimagine1** [comment]
Check if somethings blocking access to github, it works fine for me
![image](https://github.com/Overimagine1/old-discord-font/assets/79660414/42857148-6aa8-4e89-88c2-1c6725342bb2)

**Comment by Overimagine1** [comment]
closing as inactive/cant reproduce
